spring.application.name=SportFinal
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/DBProyectoSpringBoot?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=rokaxixa
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true